/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author devmat
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        areadecalculo = new javax.swing.JTextField();
        sete = new javax.swing.JButton();
        divisao = new javax.swing.JButton();
        multiplicacao = new javax.swing.JButton();
        adicao = new javax.swing.JButton();
        subtracao = new javax.swing.JButton();
        porcentagem = new javax.swing.JButton();
        apagar = new javax.swing.JButton();
        oito = new javax.swing.JButton();
        nove = new javax.swing.JButton();
        virgula = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        quatro = new javax.swing.JButton();
        parenteses = parenteses;
        limpartudo = new javax.swing.JButton();
        dois = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        um = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        igual = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        titulo.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Calculadora DevMat");

        areadecalculo.setEditable(false);
        areadecalculo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        areadecalculo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        areadecalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areadecalculoActionPerformed(evt);
            }
        });

        sete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sete.setText("7");
        sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seteActionPerformed(evt);
            }
        });

        divisao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        divisao.setText("/");
        divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisaoActionPerformed(evt);
            }
        });

        multiplicacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        multiplicacao.setText("x");

        adicao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adicao.setText("+");
        adicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicaoActionPerformed(evt);
            }
        });

        subtracao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subtracao.setText("-");
        subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtracaoActionPerformed(evt);
            }
        });

        porcentagem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        porcentagem.setText("%");
        porcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentagemActionPerformed(evt);
            }
        });

        apagar.setIcon(new javax.swing.ImageIcon("C:\\Users\\devmat\\Documents\\NetBeansProjects\\CALCULADORA\\src\\main\\java\\cancelar.png")); // NOI18N
        apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarActionPerformed(evt);
            }
        });

        oito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        oito.setText("8");
        oito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oitoActionPerformed(evt);
            }
        });

        nove.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nove.setText("9");
        nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noveActionPerformed(evt);
            }
        });

        virgula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        virgula.setText(",");

        seis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        seis.setText("6");
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        quatro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        quatro.setText("4");
        quatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quatroActionPerformed(evt);
            }
        });

        parenteses.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        parenteses.setText("()");
        parenteses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesesActionPerformed(evt);
            }
        });

        limpartudo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        limpartudo.setText("AC");
        limpartudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpartudoActionPerformed(evt);
            }
        });

        dois.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dois.setText("2");
        dois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doisActionPerformed(evt);
            }
        });

        cinco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cinco.setText("5");
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });

        um.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        um.setText("1");
        um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umActionPerformed(evt);
            }
        });

        tres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tres.setText("3");
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        zero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        igual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tituloLayout = new javax.swing.GroupLayout(titulo);
        titulo.setLayout(tituloLayout);
        tituloLayout.setHorizontalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloLayout.createSequentialGroup()
                .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tituloLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tituloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(areadecalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tituloLayout.createSequentialGroup()
                        .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tituloLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(um, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tituloLayout.createSequentialGroup()
                                .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tituloLayout.createSequentialGroup()
                                .addComponent(dois, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloLayout.createSequentialGroup()
                        .addComponent(divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adicao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(porcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloLayout.createSequentialGroup()
                        .addComponent(parenteses, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limpartudo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloLayout.createSequentialGroup()
                        .addComponent(sete, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(oito, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nove, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(virgula, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
        );
        tituloLayout.setVerticalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areadecalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tituloLayout.createSequentialGroup()
                        .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oito, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nove, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(virgula, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quatro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(limpartudo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(parenteses, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dois, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(um, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       // botão que apaga a ultima coisa digitada
    private void apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarActionPerformed
        // metodo de ação do botão
         areadecalculo.setText(areadecalculo.getText()+" ");
          // TODO add your handling code here:
          // capturando o texto digitado
          String textoAtual = areadecalculo.getText();
          // verificar se o texto está vazio ou não
          // se o texto for maior que zero
          if(textoAtual.length()>0){
              // então exclua o ultimo caracter digitado
              // substring subdivide a palavra letra por letra,
              // substring(posicaoinicial,tamanho,posicaofinal)
              textoAtual = textoAtual.substring(0,textoAtual.length()-1);//apagando a letra por letra
              areadecalculo.setText(textoAtual);
              
              
              
          }
    }//GEN-LAST:event_apagarActionPerformed

    private void divisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisaoActionPerformed
        // TODO add your handling code here:
        areadecalculo.setText(areadecalculo.getText()+"/");
    }//GEN-LAST:event_divisaoActionPerformed

    private void areadecalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areadecalculoActionPerformed
        // TODO add your handling code here:
          areadecalculo.setText(areadecalculo.getText()+" 1+1 = 10");
    }//GEN-LAST:event_areadecalculoActionPerformed

    private void umActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umActionPerformed
        // TODO add your handling code here:
         areadecalculo.setText(areadecalculo.getText()+" 1");
         
    }//GEN-LAST:event_umActionPerformed

    // metodo para calcular
    private double equacao(String expressao){
        // avaliando a expressão matemática
       return new Object(){
           // variavel de percorrer os caracteres
           int posicao = -1 ; 
           int ch;
           
           // avançar os proximos caracteres da expressao
           void nextChar(){
          // variavel do caracteres
          // lenght() ele verifica o tamanho de um texto
           ch = (++posicao < expressao.length()) ? expressao.charAt(posicao) : -1;
           }// final do nextChar()
           
           // verificando a divisao dos caracteres
             boolean eat (int valores){
                 // percorrendo o vetor até achar o espaço em branco
               while(ch ==' ')nextChar();
               // se ch for um numero então retorne verdadeiro
                  if(ch == valores){
                      nextChar();
                      return true;
                      }else{ // se não retorne falso
                         return false; // retornando falso 
                  }// final do if else   
             }// final do metodo eat
            
             // metodo para anlise principal dos calculos
             double calculando(){
                 // chamando o metodo do reconhecimento dos caracteres
                 nextChar();
                 // criando variavel de calculo x
                 double x= somarSubtrair() ;
                 // verificando se existe mais caracteres
                  if(posicao<expressao.length()) 
                      // tratando erros
                        throw new RuntimeException("Erro: "+ (char)ch);
                          return x;
             }// final do calculando
           
        // Analisar as expressões (adição)
          double somarSubtrair(){
              double x = dividirMultiplicar();
              for (;;){
                 // eat função de comparação de caractere
                // se for + ele vai somando os numeros
                if (eat('+')) x+= dividirMultiplicar(); // adição
                // se não, se for - ele vai subtraindo
               else if (eat('-')) x-= dividirMultiplicar(); // subtração
                 // se não ele só retorna
                else return x;
                 }
          } // final da soma
           
          // analisar as expressões de dividir e multiplicar
         double dividirMultiplicar(){
              double x =fatores();
              // for para ir somando
              for (;;){
                 // eat função de comparação de caractere
                // se for + ele vai somando os numeros
                if (eat('x')) x*= fatores(); // adição
                // se não, se for - ele vai subtraindo
              else if (eat('/')) x/= fatores(); // subtração
                 // se não ele só retorna
                else return x;
                 }
          } // fim do dividirmultiplicar
           // metodo para considerar o calculo dos parenteses  
          
         // calculando a porcentagem
           double porcentagem(){
               // corrigindo os erros de + e - das operações
            if (eat('+')) return porcentagem();
             if (eat('-')) return -porcentagem();
             // 100+50% x=50% y-100 z=100+50%
           // x é o valor que vai receber a porcentagem
               double x = fatores();
               // y é o valor a qual vamos adicionar a porcentagem
                double y = fatores();
                // recebe o valor que eu tinha antes e soma com a porcentagem
                double z=0;
                // se o usuário tiver digitado
                if (eat('%')){
                    x= x*y / 100;
                    x+=z;
                    
                 }// fim do if
                   return y +=x;
                         

            } // final do metodo porcentagem

               
               
               
               
               
               
           
              // metodo para considerar o calculo dos parenteses
           double fatores(){
           // corrigindo os erros de + e - das operações
             if (eat('+')) return fatores();
               if (eat('-')) return -fatores();
           int inicioPosicao = this.posicao;
           // variavel do calculo
           double x = 0;
           // procurando os parenteses();
           if(eat('(')){
             x = somarSubtrair();
             eat('(');
             // verificando os numeros digitados
           } else if((ch >= '0' && ch<='9') || ch=='.'){
               while((ch>='0' && ch<='9')|| ch=='.') nextChar();
               // converter os caracteres em numeros
               x = Double.parseDouble(expressao.substring(inicioPosicao, this.posicao));         
           }else{
             // tratando erros nas variaveis
                   throw new RuntimeException("Erros:"+ (char)ch);     
            }// final do else
           return x;
           
    }// final do metodo fatores
           
           
         }.calculando();// final do return new object

    }// final do metodo equacao    
    
    
    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        // capturar o texto da área de calculo
        // getText() - capturar o que tem escrito
        // setText() - escreve algo dentro
         try{
        String expressaoCalculo = areadecalculo.getText();
        // chamando o metodo de calcular e passando o calculo
         double resultado = equacao(expressaoCalculo);
         // passando o resultado para a área de Calculo
         areadecalculo.setText(String.valueOf(resultado));
        }catch(Exception e ){
            areadecalculo.setText("Erro no calculo"+e);
              areadecalculo.setText(areadecalculo.getText()+"=");
        }
    }//GEN-LAST:event_igualActionPerformed

    private void limpartudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpartudoActionPerformed
        // TODO add your handling code here:
      areadecalculo.setText("");
    }//GEN-LAST:event_limpartudoActionPerformed

    private void oitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oitoActionPerformed
        // TODO add your handling code here:
           areadecalculo.setText(areadecalculo.getText()+"8");
    }//GEN-LAST:event_oitoActionPerformed

    private void seteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seteActionPerformed
        // TODO add your handling code here:
          areadecalculo.setText(areadecalculo.getText()+"7");
    }//GEN-LAST:event_seteActionPerformed

    private void noveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noveActionPerformed
        // TODO add your handling code here:
          areadecalculo.setText(areadecalculo.getText()+"9");
    }//GEN-LAST:event_noveActionPerformed

    private void quatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quatroActionPerformed
        // TODO add your handling code here:
          areadecalculo.setText(areadecalculo.getText()+"4");
          
          
          
    }//GEN-LAST:event_quatroActionPerformed
     boolean parentesesAberto =false;
    private void parentesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesesActionPerformed
        // Todo add your handling code here:
        // se parentese ainda não foi aberto
        if (parentesesAberto==false){
            // parentese agor aberto
            areadecalculo.setText(areadecalculo.getText()+"(");
            // parenteses=true;
          }else{ // parentese já esta aberto
            // fechando parentese
            areadecalculo.setText(areadecalculo.getText() +")");
            parentesesAberto=false; // parentese não esta aberto mais 
            
        }
    }//GEN-LAST:event_parentesesActionPerformed

    private void adicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicaoActionPerformed
        // TODO add your handling code here:
           areadecalculo.setText(areadecalculo.getText()+"+");
    }//GEN-LAST:event_adicaoActionPerformed

    private void subtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtracaoActionPerformed
        // TODO add your handling code here:
           areadecalculo.setText(areadecalculo.getText()+"-");
    }//GEN-LAST:event_subtracaoActionPerformed

    private void porcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentagemActionPerformed
        // TODO add your handling code here:
           areadecalculo.setText(areadecalculo.getText()+"%");
    }//GEN-LAST:event_porcentagemActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        // TODO add your handling code here:
           areadecalculo.setText(areadecalculo.getText()+"5");
    }//GEN-LAST:event_cincoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        // TODO add your handling code here:
           areadecalculo.setText(areadecalculo.getText()+"6");
    }//GEN-LAST:event_seisActionPerformed

    private void doisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doisActionPerformed
        // TODO add your handling code here:
           areadecalculo.setText(areadecalculo.getText()+"2");
    }//GEN-LAST:event_doisActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        // TODO add your handling code here:
           areadecalculo.setText(areadecalculo.getText()+"3");
    }//GEN-LAST:event_tresActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:
           areadecalculo.setText(areadecalculo.getText()+"0");
    }//GEN-LAST:event_zeroActionPerformed
    
   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
        

    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicao;
    private javax.swing.JButton apagar;
    private javax.swing.JTextField areadecalculo;
    private javax.swing.JButton cinco;
    private javax.swing.JButton divisao;
    private javax.swing.JButton dois;
    private javax.swing.JButton igual;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton limpartudo;
    private javax.swing.JButton multiplicacao;
    private javax.swing.JButton nove;
    private javax.swing.JButton oito;
    private javax.swing.JButton parenteses;
    private javax.swing.JButton porcentagem;
    private javax.swing.JButton quatro;
    private javax.swing.JButton seis;
    private javax.swing.JButton sete;
    private javax.swing.JButton subtracao;
    private javax.swing.JPanel titulo;
    private javax.swing.JButton tres;
    private javax.swing.JButton um;
    private javax.swing.JButton virgula;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
